### ISSUE TITLE
About MSAR dataset

### ISSUE THREAD

**Issue by ZZQ565697818** [GrokCV/GrokSAR#4]
Excuse me，may I ask how the MSAR dataset is partitioned? If possible, could you provide the partitioned dataset? Thank you！@YimianDai @travelerwood

**Comment by travelerwood** [comment]
Thank you for feedback! Yes, the MSAR dataset has been partitioned for training, and the partition setting has been uploaded in `GrokSAR\datasets\MSAR`.  Due to space limitations, we can not upload the whole dataset to github repository. And you may find dataset resource in `https://radars.ac.cn/web/data/getData?dataType=MSAR`

**Comment by ZZQ565697818** [comment]
> Thank you for feedback! Yes, the MSAR dataset has been partitioned for training, and the partition setting has been uploaded in `GrokSAR\datasets\MSAR`. Due to space limitations, we can not upload the whole dataset to github repository. And you may find dataset resource in `https://radars.ac.cn/web/data/getData?dataType=MSAR`

你好，不好意思再次打扰您，请问一下能提供一下您处理后的数据集吗，我发现原数据集的标签似乎存在一些问题，想问问您能不能提供一下数据集，不方便上传github的话能存在网盘里然后提供一下链接吗，谢谢 @travelerwood
