### ISSUE TITLE
Performing Inference on New Data

### ISSUE THREAD

**Issue by Maatrika-P** [GrokCV/GrokSAR#8]
Hello, your work is remarkable!! I wanted to know which config/scripts are to be utilized for performing inference on unseen SAR data. I did go through all the project folders and files, I don't see any testing related scripts. Could you please help me out.

**Comment by Pwzw2022** [comment]
Hello

1. Search for a predict.py or inference.py script: These are common names for scripts designed to perform inference. If they don't exist, check if there's a main training script like train.py that might have an inference mode.
2. Look for a function within the training script: In some projects, inference might be handled by a function within the main script, usually something like predict, evaluate, or test.

**Comment by Maatrika-P** [comment]
Hi, I looked thoroughly but couldn't find any. Can you help me out with an example please?

**Comment by YimianDai** [comment]
The training and inference scripts are conveniently located in the `tools` directory. 

I apologize for any confusion caused by the lack of information in the README file. I have now updated it with clear instructions for both training and inference.

### Training

#### Single GPU Training

```shell
python tools/train_det.py configs/DenoDet/DenoDet_1x_SAR-AIRcraft-1.0.py
```

### Inference

#### Single GPU Inference

```shell
python tools/test_det.py configs/DenoDet/DenoDet_1x_SAR-AIRcraft-1.0.py {checkpoint_path}
```

To perform inference on new data, you'll need to modify the `DenoDet_1x_SAR-AIRcraft-1.0.py` configuration file and the corresponding `Dataset` class to suit your specific requirements. Please ensure that your new data follows the same format and structure as the original dataset used in this project.

Actually, this repository is built upon the powerful MMDetection framework, which provides a wealth of resources and extensive documentation. If you encounter any further questions or need additional guidance, I highly recommend referring to the MMDetection documentation ([https://mmdetection.readthedocs.io/](https://mmdetection.readthedocs.io/)). It covers a wide range of topics, including dataset preparation, model configuration, training, and inference, among others. The MMDetection community is also very active and supportive, so feel free to reach out to them for assistance.

**Comment by Maatrika-P** [comment]
Alright, I shall look into this. Thank you so much for helping out! I'll let you know how it goes.
